// Package gpuattest implements a device attestation crypto suite for Helix
// Cluster OS GPU nodes. It is pure-Go, depends only on the Go standard library
// crypto primitives, and is fully deterministic in its accept/reject outcomes.
//
// It covers four cohesive capabilities over a shared device Descriptor model:
//
//	(A) HXC-1568 — device-info challenge/response + stable fingerprint.
//	    A Verifier issues a nonce-bearing Challenge; the device signs
//	    (nonce || fingerprint || tick) with its ed25519 key. Verify accepts a
//	    genuine response and rejects expired, replayed, tampered, wrong-key and
//	    forged-descriptor responses, each with a distinct typed error.
//
//	(B) HXC-1569 — seeded matmul proof-of-GPU-work (PoVW). From a seed two NxN
//	    integer matrices are generated by a self-contained xorshift PRNG (no
//	    math/rand global, no clock). C = A*B is computed and a SHA-256 chain is
//	    folded over the rows of C. VerifyProof recomputes every link and reports
//	    the first broken link index on mismatch.
//
//	(C) HXC-1570 — O(1) spot-check verification. Each word of the proof carries a
//	    committed leaf hash inside a Merkle tree. SpotCheck verifies only the
//	    requested k indices in O(k log N) using Merkle inclusion proofs — never
//	    re-touching the other words — and names the failing index on tamper.
//
//	(D) HXC-1571 — device-sealed AES-256-GCM. SealForDevice derives a key from a
//	    device secret via HKDF-SHA256 and seals a payload under a fresh random
//	    nonce. OpenFromDevice round-trips for the sealing device and is rejected
//	    (GCM authentication failure) for any other device secret.
//
// CLAUDE-2 note: this package is platform-agnostic pure Go (no /proc, no cgroup,
// no DRM, no cgo). It runs identically on every supported OS, so it needs no
// per-OS equivalents.
package gpuattest
