// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: advisory.proto

package helixv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdvisoryService_Lock_FullMethodName       = "/helix.v1.AdvisoryService/Lock"
	AdvisoryService_Unlock_FullMethodName     = "/helix.v1.AdvisoryService/Unlock"
	AdvisoryService_TryLock_FullMethodName    = "/helix.v1.AdvisoryService/TryLock"
	AdvisoryService_WatchLocks_FullMethodName = "/helix.v1.AdvisoryService/WatchLocks"
)

// AdvisoryServiceClient is the client API for AdvisoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdvisoryServiceClient interface {
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error)
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error)
	TryLock(ctx context.Context, in *TryLockRequest, opts ...grpc.CallOption) (*TryLockResponse, error)
	WatchLocks(ctx context.Context, in *WatchLocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LockEvent], error)
}

type advisoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdvisoryServiceClient(cc grpc.ClientConnInterface) AdvisoryServiceClient {
	return &advisoryServiceClient{cc}
}

func (c *advisoryServiceClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResponse)
	err := c.cc.Invoke(ctx, AdvisoryService_Lock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advisoryServiceClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*UnlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockResponse)
	err := c.cc.Invoke(ctx, AdvisoryService_Unlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advisoryServiceClient) TryLock(ctx context.Context, in *TryLockRequest, opts ...grpc.CallOption) (*TryLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TryLockResponse)
	err := c.cc.Invoke(ctx, AdvisoryService_TryLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *advisoryServiceClient) WatchLocks(ctx context.Context, in *WatchLocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LockEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdvisoryService_ServiceDesc.Streams[0], AdvisoryService_WatchLocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchLocksRequest, LockEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdvisoryService_WatchLocksClient = grpc.ServerStreamingClient[LockEvent]

// AdvisoryServiceServer is the server API for AdvisoryService service.
// All implementations must embed UnimplementedAdvisoryServiceServer
// for forward compatibility.
type AdvisoryServiceServer interface {
	Lock(context.Context, *LockRequest) (*LockResponse, error)
	Unlock(context.Context, *UnlockRequest) (*UnlockResponse, error)
	TryLock(context.Context, *TryLockRequest) (*TryLockResponse, error)
	WatchLocks(*WatchLocksRequest, grpc.ServerStreamingServer[LockEvent]) error
	mustEmbedUnimplementedAdvisoryServiceServer()
}

// UnimplementedAdvisoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdvisoryServiceServer struct{}

func (UnimplementedAdvisoryServiceServer) Lock(context.Context, *LockRequest) (*LockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lock not implemented")
}
func (UnimplementedAdvisoryServiceServer) Unlock(context.Context, *UnlockRequest) (*UnlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlock not implemented")
}
func (UnimplementedAdvisoryServiceServer) TryLock(context.Context, *TryLockRequest) (*TryLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TryLock not implemented")
}
func (UnimplementedAdvisoryServiceServer) WatchLocks(*WatchLocksRequest, grpc.ServerStreamingServer[LockEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchLocks not implemented")
}
func (UnimplementedAdvisoryServiceServer) mustEmbedUnimplementedAdvisoryServiceServer() {}
func (UnimplementedAdvisoryServiceServer) testEmbeddedByValue()                         {}

// UnsafeAdvisoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdvisoryServiceServer will
// result in compilation errors.
type UnsafeAdvisoryServiceServer interface {
	mustEmbedUnimplementedAdvisoryServiceServer()
}

func RegisterAdvisoryServiceServer(s grpc.ServiceRegistrar, srv AdvisoryServiceServer) {
	// If the following call panics, it indicates UnimplementedAdvisoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdvisoryService_ServiceDesc, srv)
}

func _AdvisoryService_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisoryServiceServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisoryService_Lock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisoryServiceServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvisoryService_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisoryServiceServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisoryService_Unlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisoryServiceServer).Unlock(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvisoryService_TryLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TryLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdvisoryServiceServer).TryLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdvisoryService_TryLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdvisoryServiceServer).TryLock(ctx, req.(*TryLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdvisoryService_WatchLocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchLocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdvisoryServiceServer).WatchLocks(m, &grpc.GenericServerStream[WatchLocksRequest, LockEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdvisoryService_WatchLocksServer = grpc.ServerStreamingServer[LockEvent]

// AdvisoryService_ServiceDesc is the grpc.ServiceDesc for AdvisoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdvisoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helix.v1.AdvisoryService",
	HandlerType: (*AdvisoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lock",
			Handler:    _AdvisoryService_Lock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _AdvisoryService_Unlock_Handler,
		},
		{
			MethodName: "TryLock",
			Handler:    _AdvisoryService_TryLock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchLocks",
			Handler:       _AdvisoryService_WatchLocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "advisory.proto",
}
