// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: advisory.proto

package helixv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_advisory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advisory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_advisory_proto_rawDescGZIP(), []int{0}
}

func (x *LockRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *LockRequest) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LockRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acquired      bool                   `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
	LockId        string                 `protobuf:"bytes,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_advisory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advisory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_advisory_proto_rawDescGZIP(), []int{1}
}

func (x *LockResponse) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

func (x *LockResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type UnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_advisory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advisory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_advisory_proto_rawDescGZIP(), []int{2}
}

func (x *UnlockRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *UnlockRequest) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

type UnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_advisory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advisory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResponse.ProtoReflect.Descriptor instead.
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return file_advisory_proto_rawDescGZIP(), []int{3}
}

func (x *UnlockResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type TryLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryLockRequest) Reset() {
	*x = TryLockRequest{}
	mi := &file_advisory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryLockRequest) ProtoMessage() {}

func (x *TryLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advisory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryLockRequest.ProtoReflect.Descriptor instead.
func (*TryLockRequest) Descriptor() ([]byte, []int) {
	return file_advisory_proto_rawDescGZIP(), []int{4}
}

func (x *TryLockRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *TryLockRequest) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *TryLockRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type TryLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acquired      bool                   `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
	LockId        string                 `protobuf:"bytes,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryLockResponse) Reset() {
	*x = TryLockResponse{}
	mi := &file_advisory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryLockResponse) ProtoMessage() {}

func (x *TryLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advisory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryLockResponse.ProtoReflect.Descriptor instead.
func (*TryLockResponse) Descriptor() ([]byte, []int) {
	return file_advisory_proto_rawDescGZIP(), []int{5}
}

func (x *TryLockResponse) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

func (x *TryLockResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type WatchLocksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourcePrefix string                 `protobuf:"bytes,1,opt,name=resource_prefix,json=resourcePrefix,proto3" json:"resource_prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchLocksRequest) Reset() {
	*x = WatchLocksRequest{}
	mi := &file_advisory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchLocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchLocksRequest) ProtoMessage() {}

func (x *WatchLocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advisory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchLocksRequest.ProtoReflect.Descriptor instead.
func (*WatchLocksRequest) Descriptor() ([]byte, []int) {
	return file_advisory_proto_rawDescGZIP(), []int{6}
}

func (x *WatchLocksRequest) GetResourcePrefix() string {
	if x != nil {
		return x.ResourcePrefix
	}
	return ""
}

type LockEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockEvent) Reset() {
	*x = LockEvent{}
	mi := &file_advisory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockEvent) ProtoMessage() {}

func (x *LockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_advisory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockEvent.ProtoReflect.Descriptor instead.
func (*LockEvent) Descriptor() ([]byte, []int) {
	return file_advisory_proto_rawDescGZIP(), []int{7}
}

func (x *LockEvent) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *LockEvent) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LockEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LockEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_advisory_proto protoreflect.FileDescriptor

const file_advisory_proto_rawDesc = "" +
	"\n" +
	"\x0eadvisory.proto\x12\bhelix.v1\"b\n" +
	"\vLockRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"C\n" +
	"\fLockResponse\x12\x1a\n" +
	"\bacquired\x18\x01 \x01(\bR\bacquired\x12\x17\n" +
	"\alock_id\x18\x02 \x01(\tR\x06lockId\"C\n" +
	"\rUnlockRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\",\n" +
	"\x0eUnlockResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\"e\n" +
	"\x0eTryLockRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"F\n" +
	"\x0fTryLockResponse\x12\x1a\n" +
	"\bacquired\x18\x01 \x01(\bR\bacquired\x12\x17\n" +
	"\alock_id\x18\x02 \x01(\tR\x06lockId\"<\n" +
	"\x11WatchLocksRequest\x12'\n" +
	"\x0fresource_prefix\x18\x01 \x01(\tR\x0eresourcePrefix\"|\n" +
	"\tLockEvent\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\x87\x02\n" +
	"\x0fAdvisoryService\x125\n" +
	"\x04Lock\x12\x15.helix.v1.LockRequest\x1a\x16.helix.v1.LockResponse\x12;\n" +
	"\x06Unlock\x12\x17.helix.v1.UnlockRequest\x1a\x18.helix.v1.UnlockResponse\x12>\n" +
	"\aTryLock\x12\x18.helix.v1.TryLockRequest\x1a\x19.helix.v1.TryLockResponse\x12@\n" +
	"\n" +
	"WatchLocks\x12\x1b.helix.v1.WatchLocksRequest\x1a\x13.helix.v1.LockEvent0\x01B\x98\x01\n" +
	"\fcom.helix.v1B\rAdvisoryProtoP\x01Z8github.com/HelixDevelopment/helix_cluster/api/v1;helixv1\xa2\x02\x03HXX\xaa\x02\bHelix.V1\xca\x02\bHelix\\V1\xe2\x02\x14Helix\\V1\\GPBMetadata\xea\x02\tHelix::V1b\x06proto3"

var (
	file_advisory_proto_rawDescOnce sync.Once
	file_advisory_proto_rawDescData []byte
)

func file_advisory_proto_rawDescGZIP() []byte {
	file_advisory_proto_rawDescOnce.Do(func() {
		file_advisory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_advisory_proto_rawDesc), len(file_advisory_proto_rawDesc)))
	})
	return file_advisory_proto_rawDescData
}

var file_advisory_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_advisory_proto_goTypes = []any{
	(*LockRequest)(nil),       // 0: helix.v1.LockRequest
	(*LockResponse)(nil),      // 1: helix.v1.LockResponse
	(*UnlockRequest)(nil),     // 2: helix.v1.UnlockRequest
	(*UnlockResponse)(nil),    // 3: helix.v1.UnlockResponse
	(*TryLockRequest)(nil),    // 4: helix.v1.TryLockRequest
	(*TryLockResponse)(nil),   // 5: helix.v1.TryLockResponse
	(*WatchLocksRequest)(nil), // 6: helix.v1.WatchLocksRequest
	(*LockEvent)(nil),         // 7: helix.v1.LockEvent
}
var file_advisory_proto_depIdxs = []int32{
	0, // 0: helix.v1.AdvisoryService.Lock:input_type -> helix.v1.LockRequest
	2, // 1: helix.v1.AdvisoryService.Unlock:input_type -> helix.v1.UnlockRequest
	4, // 2: helix.v1.AdvisoryService.TryLock:input_type -> helix.v1.TryLockRequest
	6, // 3: helix.v1.AdvisoryService.WatchLocks:input_type -> helix.v1.WatchLocksRequest
	1, // 4: helix.v1.AdvisoryService.Lock:output_type -> helix.v1.LockResponse
	3, // 5: helix.v1.AdvisoryService.Unlock:output_type -> helix.v1.UnlockResponse
	5, // 6: helix.v1.AdvisoryService.TryLock:output_type -> helix.v1.TryLockResponse
	7, // 7: helix.v1.AdvisoryService.WatchLocks:output_type -> helix.v1.LockEvent
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_advisory_proto_init() }
func file_advisory_proto_init() {
	if File_advisory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_advisory_proto_rawDesc), len(file_advisory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_advisory_proto_goTypes,
		DependencyIndexes: file_advisory_proto_depIdxs,
		MessageInfos:      file_advisory_proto_msgTypes,
	}.Build()
	File_advisory_proto = out.File
	file_advisory_proto_goTypes = nil
	file_advisory_proto_depIdxs = nil
}
