// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: build.proto

package helixv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitBuildRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl        string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Ref            string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	DockerfilePath string                 `protobuf:"bytes,3,opt,name=dockerfile_path,json=dockerfilePath,proto3" json:"dockerfile_path,omitempty"`
	BuildArgs      map[string]string      `protobuf:"bytes,4,rep,name=build_args,json=buildArgs,proto3" json:"build_args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitBuildRequest) Reset() {
	*x = SubmitBuildRequest{}
	mi := &file_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBuildRequest) ProtoMessage() {}

func (x *SubmitBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBuildRequest.ProtoReflect.Descriptor instead.
func (*SubmitBuildRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitBuildRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *SubmitBuildRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *SubmitBuildRequest) GetDockerfilePath() string {
	if x != nil {
		return x.DockerfilePath
	}
	return ""
}

func (x *SubmitBuildRequest) GetBuildArgs() map[string]string {
	if x != nil {
		return x.BuildArgs
	}
	return nil
}

type SubmitBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Queued        bool                   `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBuildResponse) Reset() {
	*x = SubmitBuildResponse{}
	mi := &file_build_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBuildResponse) ProtoMessage() {}

func (x *SubmitBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBuildResponse.ProtoReflect.Descriptor instead.
func (*SubmitBuildResponse) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitBuildResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *SubmitBuildResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

type GetBuildStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildStatusRequest) Reset() {
	*x = GetBuildStatusRequest{}
	mi := &file_build_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildStatusRequest) ProtoMessage() {}

func (x *GetBuildStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBuildStatusRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{2}
}

func (x *GetBuildStatusRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type BuildStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	StartedAt     int64                  `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ImageTag      string                 `protobuf:"bytes,5,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStatus) Reset() {
	*x = BuildStatus{}
	mi := &file_build_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStatus) ProtoMessage() {}

func (x *BuildStatus) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStatus.ProtoReflect.Descriptor instead.
func (*BuildStatus) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{3}
}

func (x *BuildStatus) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BuildStatus) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *BuildStatus) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *BuildStatus) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

type StreamBuildLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBuildLogsRequest) Reset() {
	*x = StreamBuildLogsRequest{}
	mi := &file_build_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBuildLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBuildLogsRequest) ProtoMessage() {}

func (x *StreamBuildLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBuildLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamBuildLogsRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{4}
}

func (x *StreamBuildLogsRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type BuildLogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildLogLine) Reset() {
	*x = BuildLogLine{}
	mi := &file_build_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildLogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildLogLine) ProtoMessage() {}

func (x *BuildLogLine) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildLogLine.ProtoReflect.Descriptor instead.
func (*BuildLogLine) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{5}
}

func (x *BuildLogLine) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildLogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *BuildLogLine) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CancelBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBuildRequest) Reset() {
	*x = CancelBuildRequest{}
	mi := &file_build_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBuildRequest) ProtoMessage() {}

func (x *CancelBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBuildRequest.ProtoReflect.Descriptor instead.
func (*CancelBuildRequest) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{6}
}

func (x *CancelBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type CancelBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBuildResponse) Reset() {
	*x = CancelBuildResponse{}
	mi := &file_build_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBuildResponse) ProtoMessage() {}

func (x *CancelBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_build_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBuildResponse.ProtoReflect.Descriptor instead.
func (*CancelBuildResponse) Descriptor() ([]byte, []int) {
	return file_build_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBuildResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

var File_build_proto protoreflect.FileDescriptor

const file_build_proto_rawDesc = "" +
	"\n" +
	"\vbuild.proto\x12\bhelix.v1\"\xf4\x01\n" +
	"\x12SubmitBuildRequest\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12'\n" +
	"\x0fdockerfile_path\x18\x03 \x01(\tR\x0edockerfilePath\x12J\n" +
	"\n" +
	"build_args\x18\x04 \x03(\v2+.helix.v1.SubmitBuildRequest.BuildArgsEntryR\tbuildArgs\x1a<\n" +
	"\x0eBuildArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x13SubmitBuildResponse\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\bR\x06queued\"2\n" +
	"\x15GetBuildStatusRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"\x9d\x01\n" +
	"\vBuildStatus\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x04 \x01(\x03R\vcompletedAt\x12\x1b\n" +
	"\timage_tag\x18\x05 \x01(\tR\bimageTag\"3\n" +
	"\x16StreamBuildLogsRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"[\n" +
	"\fBuildLogLine\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"/\n" +
	"\x12CancelBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"3\n" +
	"\x13CancelBuildResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled2\xbf\x02\n" +
	"\fBuildService\x12J\n" +
	"\vSubmitBuild\x12\x1c.helix.v1.SubmitBuildRequest\x1a\x1d.helix.v1.SubmitBuildResponse\x12H\n" +
	"\x0eGetBuildStatus\x12\x1f.helix.v1.GetBuildStatusRequest\x1a\x15.helix.v1.BuildStatus\x12M\n" +
	"\x0fStreamBuildLogs\x12 .helix.v1.StreamBuildLogsRequest\x1a\x16.helix.v1.BuildLogLine0\x01\x12J\n" +
	"\vCancelBuild\x12\x1c.helix.v1.CancelBuildRequest\x1a\x1d.helix.v1.CancelBuildResponseB:Z8github.com/HelixDevelopment/helix_cluster/api/v1;helixv1b\x06proto3"

var (
	file_build_proto_rawDescOnce sync.Once
	file_build_proto_rawDescData []byte
)

func file_build_proto_rawDescGZIP() []byte {
	file_build_proto_rawDescOnce.Do(func() {
		file_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_build_proto_rawDesc), len(file_build_proto_rawDesc)))
	})
	return file_build_proto_rawDescData
}

var file_build_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_build_proto_goTypes = []any{
	(*SubmitBuildRequest)(nil),     // 0: helix.v1.SubmitBuildRequest
	(*SubmitBuildResponse)(nil),    // 1: helix.v1.SubmitBuildResponse
	(*GetBuildStatusRequest)(nil),  // 2: helix.v1.GetBuildStatusRequest
	(*BuildStatus)(nil),            // 3: helix.v1.BuildStatus
	(*StreamBuildLogsRequest)(nil), // 4: helix.v1.StreamBuildLogsRequest
	(*BuildLogLine)(nil),           // 5: helix.v1.BuildLogLine
	(*CancelBuildRequest)(nil),     // 6: helix.v1.CancelBuildRequest
	(*CancelBuildResponse)(nil),    // 7: helix.v1.CancelBuildResponse
	nil,                            // 8: helix.v1.SubmitBuildRequest.BuildArgsEntry
}
var file_build_proto_depIdxs = []int32{
	8, // 0: helix.v1.SubmitBuildRequest.build_args:type_name -> helix.v1.SubmitBuildRequest.BuildArgsEntry
	0, // 1: helix.v1.BuildService.SubmitBuild:input_type -> helix.v1.SubmitBuildRequest
	2, // 2: helix.v1.BuildService.GetBuildStatus:input_type -> helix.v1.GetBuildStatusRequest
	4, // 3: helix.v1.BuildService.StreamBuildLogs:input_type -> helix.v1.StreamBuildLogsRequest
	6, // 4: helix.v1.BuildService.CancelBuild:input_type -> helix.v1.CancelBuildRequest
	1, // 5: helix.v1.BuildService.SubmitBuild:output_type -> helix.v1.SubmitBuildResponse
	3, // 6: helix.v1.BuildService.GetBuildStatus:output_type -> helix.v1.BuildStatus
	5, // 7: helix.v1.BuildService.StreamBuildLogs:output_type -> helix.v1.BuildLogLine
	7, // 8: helix.v1.BuildService.CancelBuild:output_type -> helix.v1.CancelBuildResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_build_proto_init() }
func file_build_proto_init() {
	if File_build_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_build_proto_rawDesc), len(file_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_build_proto_goTypes,
		DependencyIndexes: file_build_proto_depIdxs,
		MessageInfos:      file_build_proto_msgTypes,
	}.Build()
	File_build_proto = out.File
	file_build_proto_goTypes = nil
	file_build_proto_depIdxs = nil
}
