// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: edge.proto

package helixv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EdgeWorkUnit (HXC-1187) is a single unit of work dispatched to an edge node.
// It carries an opaque payload plus the placement constraints (target tier and
// required capabilities) the edge runtime needs to decide whether it can run it.
type EdgeWorkUnit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id uniquely identifies this work unit; the matching EdgeWorkResult echoes it.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// payload is the opaque work body (e.g. a serialized task / blob).
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// target_tier names the node tier this unit should run on (e.g. "edge",
	// "premium"). Empty means no tier constraint.
	TargetTier string `protobuf:"bytes,3,opt,name=target_tier,json=targetTier,proto3" json:"target_tier,omitempty"`
	// capabilities lists the capabilities the executing node must provide.
	Capabilities  []*Capability `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeWorkUnit) Reset() {
	*x = EdgeWorkUnit{}
	mi := &file_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeWorkUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeWorkUnit) ProtoMessage() {}

func (x *EdgeWorkUnit) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeWorkUnit.ProtoReflect.Descriptor instead.
func (*EdgeWorkUnit) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeWorkUnit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EdgeWorkUnit) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EdgeWorkUnit) GetTargetTier() string {
	if x != nil {
		return x.TargetTier
	}
	return ""
}

func (x *EdgeWorkUnit) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// EdgeWorkResult (HXC-1187) is the outcome of executing an EdgeWorkUnit. It
// echoes the originating id and reports a terminal status plus either an output
// payload (on success) or an error message (on failure).
type EdgeWorkResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id matches the EdgeWorkUnit.id this result is for.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// status is the terminal disposition (e.g. "succeeded", "failed").
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// output is the opaque result body produced on success.
	Output []byte `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	// error carries a human-readable failure reason when status indicates failure.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeWorkResult) Reset() {
	*x = EdgeWorkResult{}
	mi := &file_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeWorkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeWorkResult) ProtoMessage() {}

func (x *EdgeWorkResult) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeWorkResult.ProtoReflect.Descriptor instead.
func (*EdgeWorkResult) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeWorkResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EdgeWorkResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EdgeWorkResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *EdgeWorkResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_edge_proto protoreflect.FileDescriptor

const file_edge_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"edge.proto\x12\bhelix.v1\x1a\vtypes.proto\"\x93\x01\n" +
	"\fEdgeWorkUnit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1f\n" +
	"\vtarget_tier\x18\x03 \x01(\tR\n" +
	"targetTier\x128\n" +
	"\fcapabilities\x18\x04 \x03(\v2\x14.helix.v1.CapabilityR\fcapabilities\"f\n" +
	"\x0eEdgeWorkResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB\x94\x01\n" +
	"\fcom.helix.v1B\tEdgeProtoP\x01Z8github.com/HelixDevelopment/helix_cluster/api/v1;helixv1\xa2\x02\x03HXX\xaa\x02\bHelix.V1\xca\x02\bHelix\\V1\xe2\x02\x14Helix\\V1\\GPBMetadata\xea\x02\tHelix::V1b\x06proto3"

var (
	file_edge_proto_rawDescOnce sync.Once
	file_edge_proto_rawDescData []byte
)

func file_edge_proto_rawDescGZIP() []byte {
	file_edge_proto_rawDescOnce.Do(func() {
		file_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)))
	})
	return file_edge_proto_rawDescData
}

var file_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_edge_proto_goTypes = []any{
	(*EdgeWorkUnit)(nil),   // 0: helix.v1.EdgeWorkUnit
	(*EdgeWorkResult)(nil), // 1: helix.v1.EdgeWorkResult
	(*Capability)(nil),     // 2: helix.v1.Capability
}
var file_edge_proto_depIdxs = []int32{
	2, // 0: helix.v1.EdgeWorkUnit.capabilities:type_name -> helix.v1.Capability
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_edge_proto_init() }
func file_edge_proto_init() {
	if File_edge_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edge_proto_goTypes,
		DependencyIndexes: file_edge_proto_depIdxs,
		MessageInfos:      file_edge_proto_msgTypes,
	}.Build()
	File_edge_proto = out.File
	file_edge_proto_goTypes = nil
	file_edge_proto_depIdxs = nil
}
