// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gpu_proxy.proto

package helixv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GPUProvider_DispatchKernel_FullMethodName       = "/helix.v1.GPUProvider/DispatchKernel"
	GPUProvider_DispatchKernelStream_FullMethodName = "/helix.v1.GPUProvider/DispatchKernelStream"
)

// GPUProviderClient is the client API for GPUProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GPUProvider (HXC-1527) is the kernel-dispatch service exposed by a GPU proxy:
// a caller submits a compute kernel plus its input buffers to a target device and
// receives the kernel's output buffer and a terminal status. A server-streaming
// variant lets long-running kernels report incremental output chunks.
type GPUProviderClient interface {
	// DispatchKernel runs a single kernel to completion and returns its output.
	DispatchKernel(ctx context.Context, in *KernelRequest, opts ...grpc.CallOption) (*KernelResponse, error)
	// DispatchKernelStream runs a kernel and streams back incremental output
	// chunks as the device produces them (e.g. partial results / progress).
	DispatchKernelStream(ctx context.Context, in *KernelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KernelChunk], error)
}

type gPUProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewGPUProviderClient(cc grpc.ClientConnInterface) GPUProviderClient {
	return &gPUProviderClient{cc}
}

func (c *gPUProviderClient) DispatchKernel(ctx context.Context, in *KernelRequest, opts ...grpc.CallOption) (*KernelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KernelResponse)
	err := c.cc.Invoke(ctx, GPUProvider_DispatchKernel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProviderClient) DispatchKernelStream(ctx context.Context, in *KernelRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KernelChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GPUProvider_ServiceDesc.Streams[0], GPUProvider_DispatchKernelStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KernelRequest, KernelChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GPUProvider_DispatchKernelStreamClient = grpc.ServerStreamingClient[KernelChunk]

// GPUProviderServer is the server API for GPUProvider service.
// All implementations must embed UnimplementedGPUProviderServer
// for forward compatibility.
//
// GPUProvider (HXC-1527) is the kernel-dispatch service exposed by a GPU proxy:
// a caller submits a compute kernel plus its input buffers to a target device and
// receives the kernel's output buffer and a terminal status. A server-streaming
// variant lets long-running kernels report incremental output chunks.
type GPUProviderServer interface {
	// DispatchKernel runs a single kernel to completion and returns its output.
	DispatchKernel(context.Context, *KernelRequest) (*KernelResponse, error)
	// DispatchKernelStream runs a kernel and streams back incremental output
	// chunks as the device produces them (e.g. partial results / progress).
	DispatchKernelStream(*KernelRequest, grpc.ServerStreamingServer[KernelChunk]) error
	mustEmbedUnimplementedGPUProviderServer()
}

// UnimplementedGPUProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGPUProviderServer struct{}

func (UnimplementedGPUProviderServer) DispatchKernel(context.Context, *KernelRequest) (*KernelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchKernel not implemented")
}
func (UnimplementedGPUProviderServer) DispatchKernelStream(*KernelRequest, grpc.ServerStreamingServer[KernelChunk]) error {
	return status.Error(codes.Unimplemented, "method DispatchKernelStream not implemented")
}
func (UnimplementedGPUProviderServer) mustEmbedUnimplementedGPUProviderServer() {}
func (UnimplementedGPUProviderServer) testEmbeddedByValue()                     {}

// UnsafeGPUProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPUProviderServer will
// result in compilation errors.
type UnsafeGPUProviderServer interface {
	mustEmbedUnimplementedGPUProviderServer()
}

func RegisterGPUProviderServer(s grpc.ServiceRegistrar, srv GPUProviderServer) {
	// If the following call panics, it indicates UnimplementedGPUProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GPUProvider_ServiceDesc, srv)
}

func _GPUProvider_DispatchKernel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KernelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProviderServer).DispatchKernel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProvider_DispatchKernel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProviderServer).DispatchKernel(ctx, req.(*KernelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProvider_DispatchKernelStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KernelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GPUProviderServer).DispatchKernelStream(m, &grpc.GenericServerStream[KernelRequest, KernelChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GPUProvider_DispatchKernelStreamServer = grpc.ServerStreamingServer[KernelChunk]

// GPUProvider_ServiceDesc is the grpc.ServiceDesc for GPUProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPUProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helix.v1.GPUProvider",
	HandlerType: (*GPUProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchKernel",
			Handler:    _GPUProvider_DispatchKernel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DispatchKernelStream",
			Handler:       _GPUProvider_DispatchKernelStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gpu_proxy.proto",
}
