// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gpu_proxy.proto

package helixv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KernelRequest carries everything the GPU proxy needs to dispatch one kernel:
// which kernel to run, on which device, with which input buffers and launch
// parameters.
type KernelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kernel_id names the kernel to execute (e.g. a registered kernel handle or
	// entry-point symbol).
	KernelId string `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`
	// device_id selects the target GPU/accelerator on the proxy.
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// args are the opaque input buffers passed to the kernel, in order.
	Args [][]byte `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// params are launch/runtime parameters (e.g. grid/block dims, flags) as
	// free-form key/value pairs.
	Params        map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelRequest) Reset() {
	*x = KernelRequest{}
	mi := &file_gpu_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelRequest) ProtoMessage() {}

func (x *KernelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelRequest.ProtoReflect.Descriptor instead.
func (*KernelRequest) Descriptor() ([]byte, []int) {
	return file_gpu_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *KernelRequest) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *KernelRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KernelRequest) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *KernelRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// KernelResponse is the terminal outcome of a DispatchKernel call: the produced
// output buffer plus a status and an optional error message.
type KernelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kernel_id echoes the request's kernel_id.
	KernelId string `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`
	// output is the opaque result buffer produced by the kernel.
	Output []byte `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// status is the terminal disposition (e.g. "ok", "error").
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// error carries a human-readable failure reason when status indicates failure.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// duration_micros is the measured device execution time in microseconds.
	DurationMicros int64 `protobuf:"varint,5,opt,name=duration_micros,json=durationMicros,proto3" json:"duration_micros,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KernelResponse) Reset() {
	*x = KernelResponse{}
	mi := &file_gpu_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelResponse) ProtoMessage() {}

func (x *KernelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelResponse.ProtoReflect.Descriptor instead.
func (*KernelResponse) Descriptor() ([]byte, []int) {
	return file_gpu_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *KernelResponse) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *KernelResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *KernelResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KernelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *KernelResponse) GetDurationMicros() int64 {
	if x != nil {
		return x.DurationMicros
	}
	return 0
}

// KernelChunk is one incremental output frame emitted by DispatchKernelStream.
// The final chunk in a stream sets last=true and carries the terminal status.
type KernelChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kernel_id echoes the request's kernel_id.
	KernelId string `protobuf:"bytes,1,opt,name=kernel_id,json=kernelId,proto3" json:"kernel_id,omitempty"`
	// sequence is the 0-based index of this chunk within the stream.
	Sequence int64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// output is the opaque output bytes for this chunk.
	Output []byte `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	// last marks the final chunk of the stream.
	Last bool `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"`
	// status is set on the final chunk to the terminal disposition.
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// error carries a failure reason on the final chunk when status indicates failure.
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelChunk) Reset() {
	*x = KernelChunk{}
	mi := &file_gpu_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelChunk) ProtoMessage() {}

func (x *KernelChunk) ProtoReflect() protoreflect.Message {
	mi := &file_gpu_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelChunk.ProtoReflect.Descriptor instead.
func (*KernelChunk) Descriptor() ([]byte, []int) {
	return file_gpu_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *KernelChunk) GetKernelId() string {
	if x != nil {
		return x.KernelId
	}
	return ""
}

func (x *KernelChunk) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *KernelChunk) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *KernelChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *KernelChunk) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KernelChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_gpu_proxy_proto protoreflect.FileDescriptor

const file_gpu_proxy_proto_rawDesc = "" +
	"\n" +
	"\x0fgpu_proxy.proto\x12\bhelix.v1\"\xd5\x01\n" +
	"\rKernelRequest\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04args\x18\x03 \x03(\fR\x04args\x12;\n" +
	"\x06params\x18\x04 \x03(\v2#.helix.v1.KernelRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\x0eKernelResponse\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12'\n" +
	"\x0fduration_micros\x18\x05 \x01(\x03R\x0edurationMicros\"\xa0\x01\n" +
	"\vKernelChunk\x12\x1b\n" +
	"\tkernel_id\x18\x01 \x01(\tR\bkernelId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x12\n" +
	"\x04last\x18\x04 \x01(\bR\x04last\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2\x9c\x01\n" +
	"\vGPUProvider\x12C\n" +
	"\x0eDispatchKernel\x12\x17.helix.v1.KernelRequest\x1a\x18.helix.v1.KernelResponse\x12H\n" +
	"\x14DispatchKernelStream\x12\x17.helix.v1.KernelRequest\x1a\x15.helix.v1.KernelChunk0\x01B\x98\x01\n" +
	"\fcom.helix.v1B\rGpuProxyProtoP\x01Z8github.com/HelixDevelopment/helix_cluster/api/v1;helixv1\xa2\x02\x03HXX\xaa\x02\bHelix.V1\xca\x02\bHelix\\V1\xe2\x02\x14Helix\\V1\\GPBMetadata\xea\x02\tHelix::V1b\x06proto3"

var (
	file_gpu_proxy_proto_rawDescOnce sync.Once
	file_gpu_proxy_proto_rawDescData []byte
)

func file_gpu_proxy_proto_rawDescGZIP() []byte {
	file_gpu_proxy_proto_rawDescOnce.Do(func() {
		file_gpu_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gpu_proxy_proto_rawDesc), len(file_gpu_proxy_proto_rawDesc)))
	})
	return file_gpu_proxy_proto_rawDescData
}

var file_gpu_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gpu_proxy_proto_goTypes = []any{
	(*KernelRequest)(nil),  // 0: helix.v1.KernelRequest
	(*KernelResponse)(nil), // 1: helix.v1.KernelResponse
	(*KernelChunk)(nil),    // 2: helix.v1.KernelChunk
	nil,                    // 3: helix.v1.KernelRequest.ParamsEntry
}
var file_gpu_proxy_proto_depIdxs = []int32{
	3, // 0: helix.v1.KernelRequest.params:type_name -> helix.v1.KernelRequest.ParamsEntry
	0, // 1: helix.v1.GPUProvider.DispatchKernel:input_type -> helix.v1.KernelRequest
	0, // 2: helix.v1.GPUProvider.DispatchKernelStream:input_type -> helix.v1.KernelRequest
	1, // 3: helix.v1.GPUProvider.DispatchKernel:output_type -> helix.v1.KernelResponse
	2, // 4: helix.v1.GPUProvider.DispatchKernelStream:output_type -> helix.v1.KernelChunk
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gpu_proxy_proto_init() }
func file_gpu_proxy_proto_init() {
	if File_gpu_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gpu_proxy_proto_rawDesc), len(file_gpu_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gpu_proxy_proto_goTypes,
		DependencyIndexes: file_gpu_proxy_proto_depIdxs,
		MessageInfos:      file_gpu_proxy_proto_msgTypes,
	}.Build()
	File_gpu_proxy_proto = out.File
	file_gpu_proxy_proto_goTypes = nil
	file_gpu_proxy_proto_depIdxs = nil
}
