// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: types.proto

package helixv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,3,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	WgPubkey      string                 `protobuf:"bytes,4,opt,name=wg_pubkey,json=wgPubkey,proto3" json:"wg_pubkey,omitempty"`
	SpiffeId      string                 `protobuf:"bytes,5,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	Resources     *NodeResources         `protobuf:"bytes,8,opt,name=resources,proto3" json:"resources,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Region        string                 `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	Version       string                 `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Node) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *Node) GetWgPubkey() string {
	if x != nil {
		return x.WgPubkey
	}
	return ""
}

func (x *Node) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

func (x *Node) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Node) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Node) GetResources() *NodeResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Node) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Node) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type NodeResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           *CPUResources          `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryResources       `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpus          []*GPUResource         `protobuf:"bytes,3,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Storage       *StorageResources      `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	Network       *NetworkResources      `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResources) Reset() {
	*x = NodeResources{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResources) ProtoMessage() {}

func (x *NodeResources) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResources.ProtoReflect.Descriptor instead.
func (*NodeResources) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *NodeResources) GetCpu() *CPUResources {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *NodeResources) GetMemory() *MemoryResources {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *NodeResources) GetGpus() []*GPUResource {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *NodeResources) GetStorage() *StorageResources {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *NodeResources) GetNetwork() *NetworkResources {
	if x != nil {
		return x.Network
	}
	return nil
}

type CPUResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arch          string                 `protobuf:"bytes,1,opt,name=arch,proto3" json:"arch,omitempty"`
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads       int32                  `protobuf:"varint,3,opt,name=threads,proto3" json:"threads,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUResources) Reset() {
	*x = CPUResources{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUResources) ProtoMessage() {}

func (x *CPUResources) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUResources.ProtoReflect.Descriptor instead.
func (*CPUResources) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *CPUResources) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *CPUResources) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUResources) GetThreads() int32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

func (x *CPUResources) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type MemoryResources struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes     int64                  `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	AvailableBytes int64                  `protobuf:"varint,2,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryResources) Reset() {
	*x = MemoryResources{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResources) ProtoMessage() {}

func (x *MemoryResources) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResources.ProtoReflect.Descriptor instead.
func (*MemoryResources) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryResources) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryResources) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

type GPUResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	DriverVersion string                 `protobuf:"bytes,4,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	Api           string                 `protobuf:"bytes,5,opt,name=api,proto3" json:"api,omitempty"`
	TotalMemory   int64                  `protobuf:"varint,6,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	ComputeUnits  int32                  `protobuf:"varint,7,opt,name=compute_units,json=computeUnits,proto3" json:"compute_units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUResource) Reset() {
	*x = GPUResource{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUResource) ProtoMessage() {}

func (x *GPUResource) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUResource.ProtoReflect.Descriptor instead.
func (*GPUResource) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *GPUResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GPUResource) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPUResource) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUResource) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GPUResource) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *GPUResource) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *GPUResource) GetComputeUnits() int32 {
	if x != nil {
		return x.ComputeUnits
	}
	return 0
}

type StorageResources struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes     int64                  `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	AvailableBytes int64                  `protobuf:"varint,2,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StorageResources) Reset() {
	*x = StorageResources{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResources) ProtoMessage() {}

func (x *StorageResources) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResources.ProtoReflect.Descriptor instead.
func (*StorageResources) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *StorageResources) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StorageResources) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

type NetworkResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []string               `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	BandwidthBps  int64                  `protobuf:"varint,2,opt,name=bandwidth_bps,json=bandwidthBps,proto3" json:"bandwidth_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkResources) Reset() {
	*x = NetworkResources{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkResources) ProtoMessage() {}

func (x *NetworkResources) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkResources.ProtoReflect.Descriptor instead.
func (*NetworkResources) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkResources) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *NetworkResources) GetBandwidthBps() int64 {
	if x != nil {
		return x.BandwidthBps
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Backend       string                 `protobuf:"bytes,6,opt,name=backend,proto3" json:"backend,omitempty"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Resources     *ResourceAllocation    `protobuf:"bytes,8,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Session) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *Session) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Session) GetResources() *ResourceAllocation {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResourceAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillicores int32                  `protobuf:"varint,1,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	GpuIds        []string               `protobuf:"bytes,3,rep,name=gpu_ids,json=gpuIds,proto3" json:"gpu_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceAllocation) Reset() {
	*x = ResourceAllocation{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceAllocation) ProtoMessage() {}

func (x *ResourceAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceAllocation.ProtoReflect.Descriptor instead.
func (*ResourceAllocation) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceAllocation) GetCpuMillicores() int32 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *ResourceAllocation) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceAllocation) GetGpuIds() []string {
	if x != nil {
		return x.GpuIds
	}
	return nil
}

type HealthScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Overall       int32                  `protobuf:"varint,2,opt,name=overall,proto3" json:"overall,omitempty"`
	Components    map[string]int32       `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthScore) Reset() {
	*x = HealthScore{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthScore) ProtoMessage() {}

func (x *HealthScore) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthScore.ProtoReflect.Descriptor instead.
func (*HealthScore) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *HealthScore) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthScore) GetOverall() int32 {
	if x != nil {
		return x.Overall
	}
	return 0
}

func (x *HealthScore) GetComponents() map[string]int32 {
	if x != nil {
		return x.Components
	}
	return nil
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Capability) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Capability) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Capability) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\bhelix.v1\"\x93\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12!\n" +
	"\fip_addresses\x18\x03 \x03(\tR\vipAddresses\x12\x1b\n" +
	"\twg_pubkey\x18\x04 \x01(\tR\bwgPubkey\x12\x1b\n" +
	"\tspiffe_id\x18\x05 \x01(\tR\bspiffeId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x125\n" +
	"\tresources\x18\b \x01(\v2\x17.helix.v1.NodeResourcesR\tresources\x122\n" +
	"\x06labels\x18\t \x03(\v2\x1a.helix.v1.Node.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06region\x18\n" +
	" \x01(\tR\x06region\x12\x18\n" +
	"\aversion\x18\v \x01(\tR\aversion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\rNodeResources\x12(\n" +
	"\x03cpu\x18\x01 \x01(\v2\x16.helix.v1.CPUResourcesR\x03cpu\x121\n" +
	"\x06memory\x18\x02 \x01(\v2\x19.helix.v1.MemoryResourcesR\x06memory\x12)\n" +
	"\x04gpus\x18\x03 \x03(\v2\x15.helix.v1.GPUResourceR\x04gpus\x124\n" +
	"\astorage\x18\x04 \x01(\v2\x1a.helix.v1.StorageResourcesR\astorage\x124\n" +
	"\anetwork\x18\x05 \x01(\v2\x1a.helix.v1.NetworkResourcesR\anetwork\"h\n" +
	"\fCPUResources\x12\x12\n" +
	"\x04arch\x18\x01 \x01(\tR\x04arch\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x18\n" +
	"\athreads\x18\x03 \x01(\x05R\athreads\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"[\n" +
	"\x0fMemoryResources\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x03R\n" +
	"totalBytes\x12'\n" +
	"\x0favailable_bytes\x18\x02 \x01(\x03R\x0eavailableBytes\"\xcc\x01\n" +
	"\vGPUResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12%\n" +
	"\x0edriver_version\x18\x04 \x01(\tR\rdriverVersion\x12\x10\n" +
	"\x03api\x18\x05 \x01(\tR\x03api\x12!\n" +
	"\ftotal_memory\x18\x06 \x01(\x03R\vtotalMemory\x12#\n" +
	"\rcompute_units\x18\a \x01(\x05R\fcomputeUnits\"\\\n" +
	"\x10StorageResources\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x03R\n" +
	"totalBytes\x12'\n" +
	"\x0favailable_bytes\x18\x02 \x01(\x03R\x0eavailableBytes\"W\n" +
	"\x10NetworkResources\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\tR\n" +
	"interfaces\x12#\n" +
	"\rbandwidth_bps\x18\x02 \x01(\x03R\fbandwidthBps\"\xde\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x18\n" +
	"\abackend\x18\x06 \x01(\tR\abackend\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12:\n" +
	"\tresources\x18\b \x01(\v2\x1c.helix.v1.ResourceAllocationR\tresources\"w\n" +
	"\x12ResourceAllocation\x12%\n" +
	"\x0ecpu_millicores\x18\x01 \x01(\x05R\rcpuMillicores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x17\n" +
	"\agpu_ids\x18\x03 \x03(\tR\x06gpuIds\"\xc6\x01\n" +
	"\vHealthScore\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aoverall\x18\x02 \x01(\x05R\aoverall\x12E\n" +
	"\n" +
	"components\x18\x03 \x03(\v2%.helix.v1.HealthScore.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xef\x01\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12D\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2$.helix.v1.Capability.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B:Z8github.com/HelixDevelopment/helix_cluster/api/v1;helixv1b\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_types_proto_goTypes = []any{
	(*Node)(nil),               // 0: helix.v1.Node
	(*NodeResources)(nil),      // 1: helix.v1.NodeResources
	(*CPUResources)(nil),       // 2: helix.v1.CPUResources
	(*MemoryResources)(nil),    // 3: helix.v1.MemoryResources
	(*GPUResource)(nil),        // 4: helix.v1.GPUResource
	(*StorageResources)(nil),   // 5: helix.v1.StorageResources
	(*NetworkResources)(nil),   // 6: helix.v1.NetworkResources
	(*Session)(nil),            // 7: helix.v1.Session
	(*ResourceAllocation)(nil), // 8: helix.v1.ResourceAllocation
	(*HealthScore)(nil),        // 9: helix.v1.HealthScore
	(*Capability)(nil),         // 10: helix.v1.Capability
	nil,                        // 11: helix.v1.Node.LabelsEntry
	nil,                        // 12: helix.v1.HealthScore.ComponentsEntry
	nil,                        // 13: helix.v1.Capability.AttributesEntry
}
var file_types_proto_depIdxs = []int32{
	1,  // 0: helix.v1.Node.resources:type_name -> helix.v1.NodeResources
	11, // 1: helix.v1.Node.labels:type_name -> helix.v1.Node.LabelsEntry
	2,  // 2: helix.v1.NodeResources.cpu:type_name -> helix.v1.CPUResources
	3,  // 3: helix.v1.NodeResources.memory:type_name -> helix.v1.MemoryResources
	4,  // 4: helix.v1.NodeResources.gpus:type_name -> helix.v1.GPUResource
	5,  // 5: helix.v1.NodeResources.storage:type_name -> helix.v1.StorageResources
	6,  // 6: helix.v1.NodeResources.network:type_name -> helix.v1.NetworkResources
	8,  // 7: helix.v1.Session.resources:type_name -> helix.v1.ResourceAllocation
	12, // 8: helix.v1.HealthScore.components:type_name -> helix.v1.HealthScore.ComponentsEntry
	13, // 9: helix.v1.Capability.attributes:type_name -> helix.v1.Capability.AttributesEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
