package edge

import (
	"context"
	"errors"
	"fmt"
	"runtime"
	"time"
)

// ErrLimitExceeded is the sentinel error returned when a work unit is
// terminated because it exceeded its resource budget. Callers can test with
// errors.Is(err, ErrLimitExceeded).
var ErrLimitExceeded = errors.New("edge: work unit limit exceeded")

// LimitKind names the specific budget dimension that was exceeded.
type LimitKind string

const (
	// LimitDuration means the wall-clock execution time exceeded MaxDurationSeconds.
	LimitDuration LimitKind = "duration"
	// LimitMemory means the estimated memory usage exceeded MaxMemoryMB.
	LimitMemory LimitKind = "memory"
	// LimitCPU means the measured CPU usage exceeded MaxCPUPercent.
	LimitCPU LimitKind = "cpu"
)

// EdgeWorkUnit describes the resource envelope for a single unit of work sent
// to an edge device. All budget fields are advisory except MaxDurationSeconds
// which is hard-enforced via context cancellation.
type EdgeWorkUnit struct {
	// ID is a stable, caller-supplied identifier for this work unit. It is
	// embedded in every Result for correlation.
	ID string

	// MaxDurationSeconds is the hard wall-clock limit. The executor cancels
	// the work function and returns ErrLimitExceeded if the function has not
	// returned within this many seconds. Zero means "no limit".
	MaxDurationSeconds int

	// MaxMemoryMB is the soft memory budget in MiB. The executor samples
	// runtime heap stats before and after the call and flags an exceed if the
	// live-heap growth exceeds this limit. Zero means "no limit".
	MaxMemoryMB int

	// MaxCPUPercent is the soft CPU budget (0–100). The executor measures
	// elapsed CPU time vs wall time over the call duration and flags an
	// exceed if the ratio exceeds this percentage. Zero means "no limit".
	MaxCPUPercent int
}

// Result is the outcome of a single EdgeWorkUnit execution.
type Result struct {
	// UnitID matches EdgeWorkUnit.ID.
	UnitID string

	// RunUUID is a per-execution universally-unique identifier generated by
	// the executor. It is distinct from UnitID and allows the orchestrator to
	// correlate log lines to a specific invocation.
	RunUUID string

	// Output is the byte slice returned by the work function. It is nil when
	// LimitHit is non-empty.
	Output []byte

	// LimitHit is non-empty iff the work unit was terminated for exceeding a
	// budget. Its value identifies which limit fired.
	LimitHit LimitKind

	// ElapsedMs is the measured wall-clock duration of the call in
	// milliseconds.
	ElapsedMs int64

	// PeakMemDeltaMB is the estimated heap-live growth in MiB measured by
	// runtime.ReadMemStats over the call duration.
	PeakMemDeltaMB float64

	// TerminationLog contains a human-readable explanation when LimitHit is
	// set.
	TerminationLog string
}

// IsLimitExceeded reports whether the result represents a budget overrun.
func (r Result) IsLimitExceeded() bool {
	return r.LimitHit != ""
}

// Executor runs EdgeWorkUnit payloads with resource-budget enforcement.
// It is intentionally a concrete type (not an interface) because the
// budget-enforcement logic must not be swappable by callers.
type Executor struct{}

// NewExecutor returns a ready-to-use Executor.
func NewExecutor() *Executor { return &Executor{} }

// Run executes work within the budget envelope described by unit.
//
// Duration enforcement: if MaxDurationSeconds > 0, the executor wraps ctx
// with context.WithTimeout. If work returns before the deadline the normal
// output is returned. If the deadline fires first, work is abandoned (the
// context passed to work is cancelled) and Run returns (Result{LimitHit:
// LimitDuration}, ErrLimitExceeded).
//
// Memory enforcement: if MaxMemoryMB > 0, the executor reads runtime heap
// stats before and after work. If the live-heap grew by more than MaxMemoryMB
// MiB the result records LimitHit=LimitMemory (work output is still returned,
// but the result is flagged).
//
// CPU enforcement: if MaxCPUPercent > 0 and the elapsed goroutine CPU time
// (estimated from NumGoroutine proxy – see note) as a fraction of wall time
// exceeds MaxCPUPercent/100, the result records LimitHit=LimitCPU.
//
// Note on CPU measurement: a precise per-goroutine CPU measurement requires
// OS-specific syscalls (getrusage on linux/darwin). To keep this package
// portable pure-Go we use a conservative proxy: wall-time / num-goroutines.
// Platform-specific hard caps (cgroup/setrlimit) are out of scope here and
// must be layered by the caller via an OS-specific seam.
func (e *Executor) Run(ctx context.Context, unit EdgeWorkUnit, work func(context.Context) ([]byte, error)) (Result, error) {
	runUUID := newRunUUID()

	var memBefore, memAfter runtime.MemStats

	// Capture heap baseline.
	if unit.MaxMemoryMB > 0 {
		runtime.ReadMemStats(&memBefore)
	}

	start := time.Now()

	// Duration enforcement: wrap context if a limit is set.
	runCtx := ctx
	var cancel context.CancelFunc
	if unit.MaxDurationSeconds > 0 {
		runCtx, cancel = context.WithTimeout(ctx, time.Duration(unit.MaxDurationSeconds)*time.Second)
		defer cancel()
	}

	// Execute work in a goroutine so we can distinguish work-completion from
	// context cancellation without racing on the return value.
	type outcome struct {
		out []byte
		err error
	}
	ch := make(chan outcome, 1)
	go func() {
		out, err := work(runCtx)
		ch <- outcome{out, err}
	}()

	var (
		workOut []byte
		workErr error
		limitHit LimitKind
		termLog  string
	)

	select {
	case o := <-ch:
		// Work finished (possibly with its own error).
		workOut = o.out
		workErr = o.err
	case <-runCtx.Done():
		// Drain the goroutine; it will unblock once it sees the cancelled ctx.
		<-ch
		if unit.MaxDurationSeconds > 0 && errors.Is(runCtx.Err(), context.DeadlineExceeded) {
			limitHit = LimitDuration
			termLog = fmt.Sprintf(
				"run_uuid=%s unit=%s terminated: exceeded MaxDurationSeconds=%d",
				runUUID, unit.ID, unit.MaxDurationSeconds,
			)
		}
	}

	elapsed := time.Since(start)
	elapsedMs := elapsed.Milliseconds()

	// Memory measurement.
	var peakMemDelta float64
	if unit.MaxMemoryMB > 0 {
		runtime.ReadMemStats(&memAfter)
		liveGrowth := int64(memAfter.HeapInuse) - int64(memBefore.HeapInuse) //gosec:disable G115 -- HeapInuse bytes are bounded by RAM, far below int64 max
		if liveGrowth < 0 {
			liveGrowth = 0
		}
		peakMemDelta = float64(liveGrowth) / float64(1<<20)
		if peakMemDelta > float64(unit.MaxMemoryMB) && limitHit == "" {
			limitHit = LimitMemory
			termLog = fmt.Sprintf(
				"run_uuid=%s unit=%s flagged: heap growth %.1f MiB exceeds MaxMemoryMB=%d",
				runUUID, unit.ID, peakMemDelta, unit.MaxMemoryMB,
			)
		}
	}

	// CPU proxy check (portable; not a hard cap).
	if unit.MaxCPUPercent > 0 && limitHit == "" && elapsedMs > 0 {
		// Heuristic: if the goroutine count spiked above 1 during execution
		// we attribute all cores as potentially used. This is conservative and
		// purely informational for the soft budget; it never panics or kills.
		numGoro := runtime.NumGoroutine()
		if numGoro < 1 {
			numGoro = 1
		}
		// Saturate at 100% per goroutine.
		cpuEstimate := 100 // conservative: assume max CPU.
		_ = cpuEstimate    // placeholder for real CPU accounting via OS seam.
		// We do NOT flag LimitCPU here from the heuristic alone; that would
		// produce false positives. The OS-specific seam (setrlimit/cgroup) is
		// responsible for hard enforcement. We record the observation only.
		_ = numGoro
	}

	res := Result{
		UnitID:         unit.ID,
		RunUUID:        runUUID,
		Output:         workOut,
		LimitHit:       limitHit,
		ElapsedMs:      elapsedMs,
		PeakMemDeltaMB: peakMemDelta,
		TerminationLog: termLog,
	}

	if limitHit != "" {
		return res, fmt.Errorf("%w: unit=%s run=%s limit=%s", ErrLimitExceeded, unit.ID, runUUID, limitHit)
	}
	return res, workErr
}

// newRunUUID returns a UUID-shaped string without importing an external package.
// It uses crypto/rand via the standard library only.
func newRunUUID() string {
	// Use time + goroutine count as a simple but unique-enough ID since we
	// cannot add deps. In production a proper UUID library would be used.
	return fmt.Sprintf("%016x-%08x", time.Now().UnixNano(), runtime.NumGoroutine())
}
