package main

// Adversarial / sink-side probes for cmd/helix-setup (the cluster bootstrap CLI).
//
// Four defect classes were mapped against the real code. SINK-SIDE verdicts
// (actual accept/reject, generated bytes across runs, files on disk) are
// asserted — never "compiles".
//
//	(a) CONFIG-VALIDATION FAIL-OPEN — Config.Validate() guards (DataDir/Prereqs/
//	    lookPath). User-supplied --cluster-name / --node-id are NOT validated.
//	    Probed below: the SINK is yaml.v3, which faithfully escapes hostile
//	    values (no YAML-key injection). The empty-cluster-name acceptance is
//	    pinned as the CURRENT (un-promised) contract — a LATENT RISK, not a
//	    violated promise.
//	(b) ARG/PARSE BYPASS — no numeric flags exist (no negative/overflow surface);
//	    the only "unsafe op" reachable from a free-string flag is file-path /
//	    YAML construction. Pinned: a newline-laden --node-id cannot inject keys.
//	(c) DETERMINISM — node-config.yaml is computed over a Go map (Labels).
//	    yaml.v3 sorts map keys, so output is byte-identical run-to-run. Proven
//	    over many iterations.
//	(d) ATOMICITY / PARTIAL-WRITE — os.WriteFile is non-atomic, and generation
//	    spans two files (config.yaml then node-config.yaml). Pinned: when the
//	    orchestrator FAILS, run() surfaces a non-OK exit and withholds the
//	    "Setup complete!" line — failure is NOT presented as complete.
//
// FINDING: NO BUG against any written contract. Determinism + injection-safety
// hold at the sink. Two LATENT RISKS are documented in-line. All tests COMPLETE
// well under -timeout 90s and use only t.TempDir().

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// ─── (c) DETERMINISM ─────────────────────────────────────────────────────────

// TestAdversarialNodeConfigDeterministic proves the generated node-config bytes
// are byte-identical across many runs despite being built over a Go map
// (NodeConfig.Labels). A non-deterministic generated config would break
// GitOps/diff workflows. yaml.v3 sorts map keys, so this holds.
//
// Bite: if ToYAML ever emitted Labels in map-iteration (random) order, two of
// these iterations would differ and the test fails.
func TestAdversarialNodeConfigDeterministic(t *testing.T) {
	hw := HardwareSummary{CPUCores: 8, MemoryMB: 16384, Tier: "T2"}

	var first []byte
	const iters = 300
	for i := 0; i < iters; i++ {
		cfg := GenerateConfig(hw, "det-cluster", "det-node")
		b, err := cfg.ToYAML()
		if err != nil {
			t.Fatalf("iter %d: ToYAML: %v", i, err)
		}
		if first == nil {
			first = b
			continue
		}
		if string(b) != string(first) {
			t.Fatalf("NON-DETERMINISTIC node-config at iter %d:\nfirst:\n%s\ngot:\n%s", i, first, b)
		}
	}
	// Sink-side: the multi-key Labels map must actually be present and ordered.
	if !strings.Contains(string(first), "cpu_cores:") || !strings.Contains(string(first), "tier:") {
		t.Fatalf("expected both label keys in output; got:\n%s", first)
	}
	// cpu_cores must sort before tier (proves stable key ordering, not luck).
	if strings.Index(string(first), "cpu_cores:") > strings.LastIndex(string(first), "tier:") {
		t.Fatalf("label keys not in sorted order; got:\n%s", first)
	}
}

// TestAdversarialRunWritesDeterministicFile proves the full run() path writes a
// byte-identical node-config.yaml across repeated runs into fresh data dirs
// (same identity inputs). This is the end-user/GitOps-visible determinism.
func TestAdversarialRunWritesDeterministicFile(t *testing.T) {
	read := func() []byte {
		dataDir := filepath.Join(t.TempDir(), ".helix")
		cfg := Config{DataDir: dataDir, Prereqs: defaultPrereqs(), lookPath: allFound, Joiner: &recordingJoiner{}}
		var out, errOut strings.Builder
		code := run(context.Background(), cfg,
			[]string{"helix-setup", "--skip-checks", "--cluster-name", "c", "--node-id", "fixed-node"},
			&out, &errOut)
		if code != exitOK {
			t.Fatalf("run exit=%d stderr=%q", code, errOut.String())
		}
		raw, err := os.ReadFile(filepath.Join(dataDir, "node-config.yaml"))
		if err != nil {
			t.Fatalf("read node-config: %v", err)
		}
		return raw
	}
	a, b := read(), read()
	if string(a) != string(b) {
		t.Fatalf("node-config.yaml differs across runs (non-deterministic):\nA:\n%s\nB:\n%s", a, b)
	}
}

// ─── (a)+(b) CONFIG-VALIDATION / INJECTION at the YAML sink ──────────────────

// TestAdversarialHostileNodeIDDoesNotInjectKeys proves a --node-id carrying
// newlines and what looks like a YAML key cannot inject a sibling key into the
// generated node-config.yaml. The serializer (yaml.v3) is the gate: it must
// emit the hostile value as a single scalar that round-trips faithfully.
//
// SINK-SIDE: we decode the produced YAML and assert (1) the injected token is
// NOT a top-level key, and (2) node_id round-trips to the exact hostile string.
func TestAdversarialHostileNodeIDDoesNotInjectKeys(t *testing.T) {
	const hostile = "evil\nmalicious_key: pwned\ninjected: true"
	dataDir := filepath.Join(t.TempDir(), ".helix")
	cfg := Config{DataDir: dataDir, Prereqs: defaultPrereqs(), lookPath: allFound, Joiner: &recordingJoiner{}}
	var out, errOut strings.Builder

	code := run(context.Background(), cfg,
		[]string{"helix-setup", "--skip-checks", "--node-id", hostile}, &out, &errOut)
	if code != exitOK {
		t.Fatalf("run exit=%d stderr=%q", code, errOut.String())
	}

	raw, err := os.ReadFile(filepath.Join(dataDir, "node-config.yaml"))
	if err != nil {
		t.Fatalf("read node-config: %v", err)
	}

	// Decode into a generic map to detect any injected sibling keys.
	var top map[string]any
	if err := yaml.Unmarshal(raw, &top); err != nil {
		t.Fatalf("produced YAML does not parse (corruption): %v\n%s", err, raw)
	}
	if _, bad := top["malicious_key"]; bad {
		t.Fatalf("YAML INJECTION: hostile --node-id created a top-level 'malicious_key':\n%s", raw)
	}
	if _, bad := top["injected"]; bad {
		t.Fatalf("YAML INJECTION: hostile --node-id created a top-level 'injected':\n%s", raw)
	}

	// node_id must round-trip to the exact hostile string (faithful escaping).
	var decoded NodeConfig
	if err := yaml.Unmarshal(raw, &decoded); err != nil {
		t.Fatalf("decode NodeConfig: %v", err)
	}
	if decoded.NodeID != hostile {
		t.Fatalf("node_id did not round-trip faithfully:\n got=%q\nwant=%q\nYAML:\n%s",
			decoded.NodeID, hostile, raw)
	}
}

// TestAdversarialEmptyClusterNameAccepted PINS the CURRENT (un-promised)
// contract: an explicitly empty --cluster-name is accepted, run() returns
// exitOK, and node-config.yaml is written with cluster_name: "".
//
// LATENT RISK: a node cannot meaningfully "join" an unnamed cluster, and the
// static config.yaml hardcodes name: helix-local, so the two files can DISAGREE
// (config.yaml=helix-local vs node-config.yaml=""). There is no written promise
// that cluster-name is non-empty, so this is documented as a risk, not a bug.
// If a non-empty-cluster-name contract is later adopted, flip this assertion to
// require a non-OK exit.
func TestAdversarialEmptyClusterNameAccepted(t *testing.T) {
	dataDir := filepath.Join(t.TempDir(), ".helix")
	joiner := &recordingJoiner{}
	cfg := Config{DataDir: dataDir, Prereqs: defaultPrereqs(), lookPath: allFound, Joiner: joiner}
	var out, errOut strings.Builder

	code := run(context.Background(), cfg,
		[]string{"helix-setup", "--skip-checks", "--cluster-name", ""}, &out, &errOut)

	// Current behaviour: accepted.
	if code != exitOK {
		t.Fatalf("empty --cluster-name unexpectedly rejected with exit=%d stderr=%q (contract changed?)",
			code, errOut.String())
	}
	raw, err := os.ReadFile(filepath.Join(dataDir, "node-config.yaml"))
	if err != nil {
		t.Fatalf("read node-config: %v", err)
	}
	var decoded NodeConfig
	if err := yaml.Unmarshal(raw, &decoded); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if decoded.ClusterName != "" {
		t.Fatalf("expected empty cluster_name pinned, got %q", decoded.ClusterName)
	}
	if joiner.receivedCfg.ClusterName != "" {
		t.Fatalf("joiner received cluster_name %q, want empty (pin)", joiner.receivedCfg.ClusterName)
	}
}

// ─── (d) ATOMICITY / PARTIAL-WRITE ───────────────────────────────────────────

// failJoiner forces the orchestrator's mesh-join step (step 6) to fail, AFTER
// both config.yaml and node-config.yaml have been written.
type failJoiner struct{}

func (failJoiner) Join(NodeConfig) error { return errOrchestratorBoom }

var errOrchestratorBoom = &joinError{}

type joinError struct{}

func (*joinError) Error() string { return "simulated mesh-join failure" }

// TestAdversarialOrchestratorFailureSurfaced proves that when generation fails
// partway (mesh-join errors after files are written), run() does NOT present the
// run as complete: it returns a non-OK exit code AND withholds the
// "Setup complete!" line. A partial run is therefore SURFACED, not bluffed.
//
// This is the honest contract for a non-atomic, multi-file generator: the only
// completeness signal an end user gets is exit==0 + "Setup complete!", and both
// are correctly withheld on failure.
//
// Bite: if run() returned exitOK after orch.Run() errored (ignoring the error),
// the exit-code assertion fails. If it printed "Setup complete!" regardless, the
// stdout assertion fails.
func TestAdversarialOrchestratorFailureSurfaced(t *testing.T) {
	dataDir := filepath.Join(t.TempDir(), ".helix")
	cfg := Config{DataDir: dataDir, Prereqs: defaultPrereqs(), lookPath: allFound, Joiner: failJoiner{}}
	var out, errOut strings.Builder

	code := run(context.Background(), cfg, []string{"helix-setup", "--skip-checks"}, &out, &errOut)

	if code == exitOK {
		t.Fatalf("orchestrator failure presented as success (exit=0); stderr=%q", errOut.String())
	}
	if code != exitWriteFail {
		t.Fatalf("exit=%d, want exitWriteFail(%d) on orchestrator failure", code, exitWriteFail)
	}
	if strings.Contains(out.String(), "Setup complete!") {
		t.Fatalf("partial/failed run was presented as complete:\n%s", out.String())
	}
	// The failure reason must reach stderr (visible to the operator/logs).
	if !strings.Contains(errOut.String(), "orchestrator failed") {
		t.Fatalf("orchestrator failure not surfaced on stderr; got:\n%s", errOut.String())
	}
}

// TestAdversarialConfigFileNotTruncatedOnRerun proves that an idempotent re-run
// never leaves config.yaml shorter/partial than the canonical content — the
// final file always equals the full configContent (no half-written artifact
// presented as complete). os.WriteFile truncates-then-writes; on success the
// file is the full payload.
func TestAdversarialConfigFileNotTruncatedOnRerun(t *testing.T) {
	dataDir := filepath.Join(t.TempDir(), ".helix")
	cfg := Config{DataDir: dataDir, Prereqs: defaultPrereqs(), lookPath: allFound, Joiner: &recordingJoiner{}}
	for i := 0; i < 3; i++ {
		var out, errOut strings.Builder
		if code := run(context.Background(), cfg, []string{"helix-setup", "--skip-checks"}, &out, &errOut); code != exitOK {
			t.Fatalf("run %d exit=%d stderr=%q", i, code, errOut.String())
		}
		got, err := os.ReadFile(filepath.Join(dataDir, configFileName))
		if err != nil {
			t.Fatalf("run %d: read config.yaml: %v", i, err)
		}
		if string(got) != configContent {
			t.Fatalf("run %d: config.yaml not the full canonical content (partial/corrupt):\n%s", i, got)
		}
	}
}
