//go:build integration

package computeproto_test

// Integration test: generate a C++ header via real 'flatc --cpp', compile a
// tiny C++ consumer harness with clang++, write the same buffer (carrying a
// per-run UUID in ComputeTask.id) to a temp file, run the harness, and assert
// exit 0 + the per-run UUID in stdout.  Hard-FAIL on dim mismatch.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/uuid"

	"github.com/HelixDevelopment/helix_cluster/pkg/computeproto"
)

// cppHarnessSrc is the C++ consumer that reads the FlatBuffer from argv[1]
// and asserts the tensor dimensions and prints the id.
// Hard-fails (exit 1) on any mismatch so the Go test can check exit status.
const cppHarnessSrc = `
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <fstream>
#include "compute_generated.h"   // generated by flatc --cpp

static void die(const char* msg) {
    fprintf(stderr, "FAIL: %s\n", msg);
    exit(1);
}

int main(int argc, char** argv) {
    if (argc < 2) die("usage: harness <buffer-file>");

    // Read buffer file.
    std::ifstream f(argv[1], std::ios::binary | std::ios::ate);
    if (!f) die("cannot open buffer file");
    std::streamsize sz = f.tellg();
    f.seekg(0, std::ios::beg);
    std::vector<uint8_t> buf(sz);
    if (!f.read(reinterpret_cast<char*>(buf.data()), sz)) die("read failed");

    const auto* task = computeproto::GetComputeTask(buf.data());
    if (!task) die("null ComputeTask");

    // Print id so the Go test can assert the per-run UUID.
    printf("id=%s\n", task->id()->c_str());

    // Assert 2 inputs.
    if (task->inputs() == nullptr || task->inputs()->size() != 2)
        die("inputs count mismatch: expected 2");

    // Input[0]: weight, dims [512, 1024], dtype float16
    const auto* w = task->inputs()->Get(0);
    if (strcmp(w->name()->c_str(), "weight") != 0) die("input[0] name mismatch");
    if (w->dims() == nullptr || w->dims()->size() != 2) die("input[0] dims length mismatch");
    if ((*w->dims())[0] != 512) die("input[0] dims[0] mismatch: expected 512");
    if ((*w->dims())[1] != 1024) die("input[0] dims[1] mismatch: expected 1024");
    if (strcmp(w->dtype()->c_str(), "float16") != 0) die("input[0] dtype mismatch");

    // Input[1]: activation, dims [32, 512], dtype float16
    const auto* a = task->inputs()->Get(1);
    if (strcmp(a->name()->c_str(), "activation") != 0) die("input[1] name mismatch");
    if (a->dims() == nullptr || a->dims()->size() != 2) die("input[1] dims length mismatch");
    if ((*a->dims())[0] != 32)  die("input[1] dims[0] mismatch: expected 32");
    if ((*a->dims())[1] != 512) die("input[1] dims[1] mismatch: expected 512");
    if (strcmp(a->dtype()->c_str(), "float16") != 0) die("input[1] dtype mismatch");

    // 1 output: result, dims [32, 1024], dtype float32
    if (task->outputs() == nullptr || task->outputs()->size() != 1)
        die("outputs count mismatch: expected 1");
    const auto* r = task->outputs()->Get(0);
    if (strcmp(r->name()->c_str(), "result") != 0) die("output[0] name mismatch");
    if (r->dims() == nullptr || r->dims()->size() != 2) die("output[0] dims length mismatch");
    if ((*r->dims())[0] != 32)   die("output[0] dims[0] mismatch: expected 32");
    if ((*r->dims())[1] != 1024) die("output[0] dims[1] mismatch: expected 1024");
    if (strcmp(r->dtype()->c_str(), "float32") != 0) die("output[0] dtype mismatch");

    printf("dims_ok\n");
    return 0;
}
`

func TestIntegration_CppConsumerReadsBuffer(t *testing.T) {
	// Skip if external tools are absent.
	if _, err := exec.LookPath("flatc"); err != nil {
		t.Skip("flatc not found on PATH; skipping C++ integration test")
	}
	if _, err := exec.LookPath("clang++"); err != nil {
		t.Skip("clang++ not found on PATH; skipping C++ integration test")
	}

	// Per-run UUID embedded in ComputeTask.id.
	runID := uuid.New().String()

	// Build the spec with the per-run UUID as ID.
	spec := computeproto.ComputeTaskSpec{
		ID:     runID,
		Kernel: "matmul_fp16",
		Inputs: []computeproto.TensorSpec{
			{Name: "weight", Dims: []int32{512, 1024}, Dtype: "float16"},
			{Name: "activation", Dims: []int32{32, 512}, Dtype: "float16"},
		},
		Outputs: []computeproto.TensorSpec{
			{Name: "result", Dims: []int32{32, 1024}, Dtype: "float32"},
		},
	}
	bufBytes := computeproto.BuildComputeTask(spec)

	// Work directory for temp files.
	tmpDir := t.TempDir()

	// ── step 1: generate C++ header ──────────────────────────────────────────
	// Source schema lives next to this test file.
	schemaPath := filepath.Join(".", "compute.fbs")
	absSchema, err := filepath.Abs(schemaPath)
	if err != nil {
		t.Fatalf("abs schema path: %v", err)
	}

	genOut, err := exec.Command("flatc", "--cpp", "-o", tmpDir, absSchema).CombinedOutput()
	if err != nil {
		t.Fatalf("flatc --cpp failed: %v\n%s", err, genOut)
	}

	// ── step 2: write buffer to temp file ────────────────────────────────────
	bufFile := filepath.Join(tmpDir, "compute_task.bin")
	if err := os.WriteFile(bufFile, bufBytes, 0o600); err != nil {
		t.Fatalf("write buffer file: %v", err)
	}

	// ── step 3: write C++ harness source ─────────────────────────────────────
	srcFile := filepath.Join(tmpDir, "harness.cpp")
	if err := os.WriteFile(srcFile, []byte(cppHarnessSrc), 0o600); err != nil {
		t.Fatalf("write harness src: %v", err)
	}

	// ── step 4: compile harness ──────────────────────────────────────────────
	// FlatBuffers C++ header include path: find the flatbuffers include dir.
	fbInclude := findFlatbuffersInclude(t)
	binaryPath := filepath.Join(tmpDir, "harness")
	compileOut, err := exec.Command(
		"clang++",
		"-std=c++17",
		"-I", tmpDir,       // for compute_generated.h
		"-I", fbInclude,    // for flatbuffers/flatbuffers.h
		"-o", binaryPath,
		srcFile,
	).CombinedOutput()
	if err != nil {
		t.Fatalf("clang++ compile failed: %v\n%s", err, compileOut)
	}

	// ── step 5: run harness ──────────────────────────────────────────────────
	runOut, err := exec.Command(binaryPath, bufFile).CombinedOutput()
	if err != nil {
		t.Fatalf("harness exited non-zero: %v\nstdout/err:\n%s", err, runOut)
	}

	outStr := string(runOut)
	t.Logf("harness output: %s", outStr)

	// Assert per-run UUID appears in output.
	expectedIDLine := fmt.Sprintf("id=%s", runID)
	if !strings.Contains(outStr, expectedIDLine) {
		t.Errorf("per-run UUID %q not found in harness output:\n%s", runID, outStr)
	}

	// Assert dims_ok sentinel printed.
	if !strings.Contains(outStr, "dims_ok") {
		t.Errorf("\"dims_ok\" sentinel not found in harness output:\n%s", outStr)
	}
}

// findFlatbuffersInclude locates the flatbuffers C++ include directory.
// It checks common Homebrew locations and the Go module cache.
func findFlatbuffersInclude(t *testing.T) string {
	t.Helper()
	candidates := []string{
		"/opt/homebrew/include",
		"/usr/local/include",
		"/usr/include",
	}
	for _, c := range candidates {
		if _, err := os.Stat(filepath.Join(c, "flatbuffers", "flatbuffers.h")); err == nil {
			return c
		}
	}
	// Try to locate via pkg-config.
	out, err := exec.Command("pkg-config", "--cflags-only-I", "flatbuffers").Output()
	if err == nil && len(out) > 0 {
		return strings.TrimPrefix(strings.TrimSpace(string(out)), "-I")
	}
	t.Skip("flatbuffers C++ headers not found; skipping C++ integration test")
	return ""
}
