// Package serde — Cap'n Proto zero-copy serialization for control-plane Node.
// node.capnp.go is generated by capnpc-go from node.capnp; do NOT edit it.
package serde

import (
	capnp "capnproto.org/go/capnp/v3"
)

// NodeRecord is the Go-side representation of a control-plane node.
// It bridges to/from the generated Cap'n Proto Node struct.
type NodeRecord struct {
	ID       string
	Hostname string
	Cores    uint32
	MemBytes uint64
	Labels   []string
}

// MarshalNode serialises n into a framed Cap'n Proto message byte slice.
// The returned bytes own their own memory and may be stored or transmitted.
func MarshalNode(n NodeRecord) ([]byte, error) {
	msg, seg, err := capnp.NewMessage(capnp.SingleSegment(nil))
	if err != nil {
		return nil, err
	}

	root, err := NewRootNode(seg)
	if err != nil {
		return nil, err
	}

	if err := root.SetId(n.ID); err != nil {
		return nil, err
	}
	if err := root.SetHostname(n.Hostname); err != nil {
		return nil, err
	}
	root.SetCores(n.Cores)
	root.SetMemBytes(n.MemBytes)

	if len(n.Labels) > 0 {
		lbls, err := root.NewLabels(int32(len(n.Labels)))
		if err != nil {
			return nil, err
		}
		for i, l := range n.Labels {
			if err := lbls.Set(i, l); err != nil {
				return nil, err
			}
		}
	}

	return msg.Marshal()
}

// NodeView is a zero-copy view of a deserialised Node.
// Field accessors read directly from the underlying message buffer;
// no per-field heap allocation occurs after the initial Unmarshal.
type NodeView struct {
	// msg holds the backing memory; it must remain live for the view's lifetime.
	msg  *capnp.Message
	node Node // generated capnp struct — a thin wrapper over msg segment bytes
}

// DeserializeNode parses a framed Cap'n Proto message and returns a zero-copy
// NodeView backed by data.  The caller must not modify data while the view is
// in use.  No per-field copy is made; Id()/Hostname()/Labels() read straight
// from the segment buffer.
func DeserializeNode(data []byte) (*NodeView, error) {
	msg, err := capnp.Unmarshal(data)
	if err != nil {
		return nil, err
	}
	node, err := ReadRootNode(msg)
	if err != nil {
		return nil, err
	}
	return &NodeView{msg: msg, node: node}, nil
}

// Id returns the node's ID string directly from the message segment (zero-copy).
func (v *NodeView) Id() (string, error) { return v.node.Id() }

// Hostname returns the node's hostname directly from the message segment (zero-copy).
func (v *NodeView) Hostname() (string, error) { return v.node.Hostname() }

// Cores returns the node's CPU core count.
func (v *NodeView) Cores() uint32 { return v.node.Cores() }

// MemBytes returns the node's memory size in bytes.
func (v *NodeView) MemBytes() uint64 { return v.node.MemBytes() }

// Labels returns the raw capnp.TextList backed by the segment (zero-copy).
// Callers iterate with l.At(i) which reads bytes from the segment directly.
func (v *NodeView) Labels() (capnp.TextList, error) { return v.node.Labels() }

// ToRecord materialises a fully-copied NodeRecord from the zero-copy view.
// Use this only when you need a value that outlives the backing buffer.
func (v *NodeView) ToRecord() (NodeRecord, error) {
	id, err := v.node.Id()
	if err != nil {
		return NodeRecord{}, err
	}
	hostname, err := v.node.Hostname()
	if err != nil {
		return NodeRecord{}, err
	}
	lblList, err := v.node.Labels()
	if err != nil {
		return NodeRecord{}, err
	}
	labels := make([]string, lblList.Len())
	for i := range labels {
		s, err := lblList.At(i)
		if err != nil {
			return NodeRecord{}, err
		}
		labels[i] = s
	}
	return NodeRecord{
		ID:       id,
		Hostname: hostname,
		Cores:    v.node.Cores(),
		MemBytes: v.node.MemBytes(),
		Labels:   labels,
	}, nil
}
