// Code generated by capnpc-go. DO NOT EDIT.

package serde

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Node capnp.Struct

// Node_TypeID is the unique identifier for the type Node.
const Node_TypeID = 0xdec952a390f3ca8b

func NewNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return Node(st), err
}

func NewRootNode(s *capnp.Segment) (Node, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3})
	return Node(st), err
}

func ReadRootNode(msg *capnp.Message) (Node, error) {
	root, err := msg.Root()
	return Node(root.Struct()), err
}

func (s Node) String() string {
	str, _ := text.Marshal(0xdec952a390f3ca8b, capnp.Struct(s))
	return str
}

func (s Node) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Node) DecodeFromPtr(p capnp.Ptr) Node {
	return Node(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Node) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Node) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Node) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Node) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Node) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Node) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Node) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Node) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Node) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Node) HasHostname() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Node) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Node) SetHostname(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Node) Cores() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s Node) SetCores(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s Node) MemBytes() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Node) SetMemBytes(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s Node) Labels() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s Node) HasLabels() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Node) SetLabels(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewLabels sets the labels field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s Node) NewLabels(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// Node_List is a list of Node.
type Node_List = capnp.StructList[Node]

// NewNode creates a new list of Node.
func NewNode_List(s *capnp.Segment, sz int32) (Node_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 3}, sz)
	return capnp.StructList[Node](l), err
}

// Node_Future is a wrapper for a Node promised by a client call.
type Node_Future struct{ *capnp.Future }

func (f Node_Future) Struct() (Node, error) {
	p, err := f.Future.Ptr()
	return Node(p.Struct()), err
}

const schema_b3d4e5f6a7c8d9e0 = "x\xda4\xcb1J3Q\x14\x86\xe1\xef;g\xf2'" +
	"\xe1\x8f\xc1\x0b\xb7\xb2\xc9\x0a\x14b\x99F\xb1\xb4\x90\x1c" +
	"w\x103\x17\x1423\xc1I\xa1\x85\xa0\x92F\x8c0" +
	"\x08\x82\xbd\x85\x8d\x9d\x0b\xb0\x0a\x18k\x1b\x1b\xb1q\x05" +
	"\x82\xed\xc8\x08\xb6/\xcf\xbb|\xbd\x19u\x97\x9e\x081" +
	"_\xfbW^\xbe|\x15w\xbb\x8bw\xd8\x7fJ\xf9\xf1" +
	"\xf6|\xff\xfd\xf9\xfa\x88\x9a\xd6\x017?w\x8b:\xd0" +
	"\x9dw\x88\xd52\xcd\xe2\xb06\x1c\x8c\x99\x8e{;Y" +
	"\x1c\xd0'\xcdk\x04D\x04\xdc\xc9\x0a`GJ\x9b\x0a" +
	"\x1d\xe9Y\xc5\xb3m\xc0N\x956\x13R<\x05p\x17" +
	"\xeb\x80M\x95V\x08\x9d\xd2S\x01wU\xc1\x99\xd2n" +
	"\x85.\x12\xcf\x08p7=\xc0\x0a\xa5=\x08\xf5 f" +
	"\x0b\xc2\x16X\xeeg\xf9$\x1d$\x01\xc0_\xeb\x0c\xb3" +
	"\xc3\x90\xb3\x01a\x03,\x93\x90l\x1dOB^\x89&" +
	"\x84Mpc4\xd8\x0b\xa3\x9cm\xb0\xaf\xfc\xfd\xda\xe0" +
	"O\x00\x00\x00\xff\xff@\xc58p"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_b3d4e5f6a7c8d9e0,
		Nodes: []uint64{
			0xdec952a390f3ca8b,
		},
		Compressed: true,
	})
}
